name: CI-CD

on:
  push:
    branches: ["main"]
  workflow_dispatch:

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout do Repositorio Github
      uses: actions/checkout@v4.1.1

    - name: Docker Login
      uses: docker/login-action@v3.0.0
      with:
        username: ${{ secrets.dockerhub_usr }}
        password: ${{ secrets.dockerhub_pwd }}
        
    - name: Build and push Docker images
      uses: docker/build-push-action@v5.0.0
      with:
        context: ./kube-news/src
        file: ./kube-news/src/Dockerfile
        push: true
        tags: |
          ericonp/kube-news:${{ github.run_number }}
          ericonp/kube-news:latest


  CD:
    runs-on: ubuntu-latest
    needs: [CI]
    steps:
    - name: Checkout do Repositorio Github
      uses: actions/checkout@v4.1.1

    - name: Configuracao da credencial AWS
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.aws_key }}
        aws-secret-access-key: ${{ secrets.aws_secret_key }}
        aws-region: us-east-1

    - name: Configurar o KubeConfig
      run: aws eks update-kubeconfig --name ${{ secrets.aws_nome_cluster_eks }}
      
    - name: Aplicar o deploy
      uses: Azure/k8s-deploy@v4.9
      with:
        manifests: |
          ./kube-news/k8s/deployment.yaml
          images: |
            hub.docker.com/repository/docker/ericonp/kube-news:${{ github.run_number }}
